[package]
name = "txt2048"
version = "0.1.0"
authors = ["Oleksandr Pushkar <alexanderpushkar86@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
